version: 2

references:
  workspace: &workspace
               /go/src/github.com/ciaranRoche/r3x/r3x-cli

  run_tests: &run_tests
    run:
      name: "Build and Run All Tests"
      command: |
        mkdir -p bin
        curl -Lso bin/shellcheck https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.6/shellcheck
        chmod +x bin/shellcheck
        go get -t -v ./...
        go get github.com/mattn/goveralls
        PATH=$PATH:$PWD/bin go test -v ./...
        go build
        if [ -z $NOVET ]; then
          diff -u <(echo -n) <(go vet . 2>&1 | grep -vE 'ExampleCommand|bash_completions.*Fprint');
        fi
        /go/bin/goveralls -coverprofile=/home/ubuntu/coverage-all.out -service=circle-ci -repotoken=ElpAmh224c6d7FHeeBJkp31RSni1CeDUa


jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: *workspace
    steps:
      - checkout
      - *run_tests
